### PR TITLE
Fix the test setup script.

### PR DESCRIPTION
**Pull request by vpetrovykh**
Make the get_setup_script match the same method from edb.

### CODE REVIEW

**Comment by vpetrovykh** [comment]
This looks like an oversight. 

Generally I wanted to use the test framework from edgedb in the tutorial, so that I can set up and tear down a test database and all that. So I was rather happy to find all the familiar base test classes in `edgedb`. I assume that we actually want these test classes duplicated between `edgedb` and `edb`.

**Comment by vpetrovykh** [comment]
> So what does this change "fix"? The new code seems to be almost 100% equivalent to the old code.

The migration command was all wrong using old-style migrations: not wrapping things in modules and incorporating module name into migration name.

**Comment by 1st1** [comment]
> The migration command was all wrong using old-style migrations: not wrapping things in modules and incorporating module name into migration name.

The commit message doesn't reflect that... Please amend and merge.

**Comment by vpetrovykh** [comment]
I've updated the `.flake8` with the same ignore codes as we use in main `edgedb` repo just to be consistent and to shut up complaints about f-strings without actual interpolated args. Aside from that I also updated the code to wrap migrations into transactions (which was giving me problems when run with `make quicktest`).

**Comment by 1st1** [comment]
Thanks, Victor!

**Pull request merged**
