### PR TITLE
Disallow passing int-like objects as <int*> arguments

### LINKED ISSUE #53: Disallow passing objects with __int__ as <int> arguments

### PR DESCRIPTION
**Pull request by ambv**
Fixes #53

### CODE REVIEW

**Comment by agritheory** [comment]
> Please also restrict inputs to `decimal` to accept integers and and Decimal.

Clarification: You're referring to the GP scalar 'decimal' not the python class Decimal, correct? In my experience string-to-decimal conversion for the python Decimal object is pretty crucial.

**Comment by elprans** [comment]
I'm referring to what's allowed to be passed as an argument to a query with a `std::decimal` parameter.  We chose to be strict and only allow passing Python `int` and `decimal.Decimal`.

**Comment by agritheory** [comment]
Thank you for that. I have a related question about scalars, but it's better suited for the chat.

**Comment by 1st1** [comment]
Please squash into one commit before merging.

**Comment by dimaqq** [comment]
OT: is this your new job, @ambv ? :)

**Comment by ambv** [comment]
> OT: is this your new job, @ambv ? :)

It is. [Not so new anymore](https://twitter.com/llanga/status/1179354806537932802) actually. :-)

**Pull request merged**
